# 第一阶段：构建和安装依赖项
FROM nvcr.io/nvidia/cuda:11.4.1-cudnn8-devel-ubuntu20.04 AS builder

# 设置环境变量
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

# 设置时区
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 更新包列表并安装必要的依赖项
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-dev \
    python3-numpy \
    && rm -rf /var/lib/apt/lists/*

# 安装 MindSpore 和 ONNX Runtime
RUN pip3 install onnxruntime-gpu

# 安装 Flask
RUN pip3 install flask




# 第二阶段：最终镜像
FROM nvcr.io/nvidia/cuda:11.4.1-cudnn8-runtime-ubuntu20.04

# 设置环境变量
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

# 设置时区
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 更新包列表并安装 Python 3 运行时
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    && rm -rf /var/lib/apt/lists/*

# 从构建阶段复制依赖项和项目文件
COPY --from=builder /usr/local/lib/python3.8/dist-packages/ /usr/local/lib/python3.8/dist-packages/
COPY --from=builder /usr/local/bin/pip3 /usr/local/bin/pip3
COPY --from=builder /usr/local/bin/python3 /usr/local/bin/python3

# 复制项目文件到镜像中
COPY . /app

# 设置工作目录
WORKDIR /app

# 定义容器启动时默认执行的命令
CMD ["python3", "one_test_quantiDCE_onnx_failed.py"]