# 使用官方的 Python 3.10.6 镜像作为基础镜像
FROM python:3.10.6-slim

# 设置工作目录
WORKDIR /app

# 只复制必要的文件和目录
COPY one_total_function.py /app/
COPY dataneeded /app/dataneeded
COPY src /app/src
COPY user_chat /app/user_chat
COPY requirements.txt /app/

# 安装依赖
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# 暴露容器的 5000 端口
EXPOSE 5000

# 在容器启动时运行的命令
CMD ["python", "one_total_function.py"]